/**
 * Curated homepage showcase media: real local video files, not generated by
 * Slate and never labelled as if they were. Every clip has a poster extracted
 * from its own frames, which is what shows before playback, when autoplay is
 * refused, and under reduced motion.
 *
 * Keyed by role, so replacing a file is a one-line change here.
 */
export interface ShowcaseMedia {
  src: string
  poster: string
  /** Accessible description of what the clip shows. */
  label: string
}

const V = '/media/videos'
const STILLS = '/media/stills'

export interface HeroMedia extends ShowcaseMedia {
  /** How long it stays up, in ms. Always shorter than the clip, so a clip is
   *  left before it would loop back to its first frame. */
  hold: number
}

/**
 * The hero rotation. Each clip is paired with a still extracted from its own
 * frames, which is its poster, its fallback, and what Stills mode shows.
 */
export const HERO_MEDIA: HeroMedia[] = [
  {
    src: `${V}/slate-hero.mp4`, poster: `${STILLS}/hero-still-01.jpg`, hold: 5600,
    label: 'People crossing a rain-soaked city street at dusk',
  },
  {
    src: `${V}/hero-02.mp4`, poster: `${STILLS}/hero-still-02.jpg`, hold: 5600,
    label: 'A woman in a knit sweater standing among desert dunes beneath snow-capped mountains',
  },
  {
    src: `${V}/hero-03.mp4`, poster: `${STILLS}/hero-still-03.jpg`, hold: 5600,
    label: 'A white running shoe on a concrete plinth in a rain-soaked neon street',
  },
  {
    // A 5.04s clip: it hands over just before it ends.
    src: `${V}/hero-04.mp4`, poster: `${STILLS}/hero-still-04.jpg`, hold: 4800,
    label: 'A lone figure at the end of a long mirrored corridor lit by softboxes',
  },
]

export const SHOWCASE = {
  video: {
    src: `${V}/video-city.mp4`,
    poster: `${V}/posters/video-city.jpg`,
    label: 'A woman walking along a wet city pavement at dusk',
  },
  // The supplied "camera-motion-landscape" clip is a café portrait, so it is
  // used as the Image showcase. The Camera Motion tile keeps Slate's own live
  // camera-move preview until a landscape clip is supplied.
  image: {
    src: `${V}/camera-motion-landscape.mp4`,
    poster: `${V}/posters/camera-motion-landscape.jpg`,
    label: 'Portrait of a young man in a café by the window',
  },
  featured: {
    src: `${V}/red-ferrari.mp4`,
    poster: `${V}/posters/red-ferrari.jpg`,
    label: 'A red sports car driving through a city at night',
  },
} satisfies Record<string, ShowcaseMedia>
